FROM golang:1.25-alpine
RUN apk add --no-cache git make curl
RUN go install github.com/cosmtrek/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN mkdir -p /tmp/air
EXPOSE 8080
ENTRYPOINT ["air", "-c", ".air.toml"]
